### ISSUE TITLE
Dependency on firebase-client-jvm breaks figwheel in my cljs project

### ISSUE THREAD

**Issue by darwin** [crisptrutski/matchbox#19] opened 2015-02-23 00:07 UTC
I added matchbox dependency into my cljs project "faceboard":
https://github.com/darwin/faceboard/commit/36f3afb32f36734c101a72d852d44c3f05a02a41

And `lein figwheel` command started immediately failing in the context of faceboard:
https://gist.github.com/darwin/9ec915d8c4d7efac3dda

Google is silent about this problem. After playing with local checkout of matchbox, I figured out that the problem is dependency on clj library. Commenting it out solved the problem:

    [com.firebase/firebase-client-jvm "2.2.0"]

I don't know if this is a figwheel issue or matchbox's. The error is rather cryptic. I assume that depending on clj library in cljs land is problematic and dependencies should exclude that library in cljs mode. I don't know much about cljx machinery tough.

**Comment by crisptrutski** [comment] 2015-02-23 06:27
Thanks for the detailed report. 

I've been using figwheel without issue, launching it from the REPL not the command line though. Other quick thoughts are perhaps interaction with other dependencies or an older JDK are at fault.

Will try reproduce this evening. Which version of Java are you using? 

Open to removing the android dependency and leaving up to users to provide, as imagine most usage from Clojurescript. 

Recommend using :exclusions in your project in the mean time so you don't need to vendor Matchbox.

**Comment by darwin** [comment] 2015-02-23 06:32
> java -version
    java version "1.8.0_25"
    Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Thanks for the :exclusions tip. I figured that out after more googling. 

Now I'm using from my project:

    [matchbox "0.0.5-SNAPSHOT" :exclusions [com.firebase/firebase-client-jvm]]

btw. namespaces/examples/docs are pretty out of sync. I got it working by reading sources and inspecting jar content. For example had to require sunog ns.

**Comment by crisptrutski** [comment] 2015-02-23 08:22
Re: sunog ns, looks like I bungled my last deployment (stale classes), see #17. Should be fixed now

**Comment by crisptrutski** [comment] 2015-02-23 12:58
@darwin had a quick look at this, and the problem lies with transitive dependencies.

`firebase-client-jvm`  requires `[org.apache.httpcomponents/httpclient "4.0.1"]`
`lein-figwheel` requires `[org.apache.httpcomponents/httpclient "4.1.2"]`

It seems that firebase "wins", and then lein-figwheel croaks on the old version. Version resolution in leiningen makes very little sense to me, and seems to inherit some truly bizarre behaviour from Maven, particularly with respect to version ranges. Have no idea why it's picking the older version here.

This also explains why I hadn't seen the issue using figwheel directly from the REPL.

Not sure the best way to go forward. Perhaps leave JVM users to manually add the dependency, although dislike the lack of symettry then that `cljsjs.firebase` is always included.

**Comment by crisptrutski** [comment] 2015-02-23 12:59
Tried using this branch with your project, and the problem vanishes https://github.com/crisptrutski/matchbox/tree/figwheel-woes. This likely breaks other users though :weary:

**Comment by crisptrutski** [comment] 2015-02-23 13:04
@darwin forcing the newer version of `httpclient` doesn't seem to cause any issues, merged a lacklustre fix for this - may require patching again with future lein-figwheel version.

**Closed by crisptrutski** 2015-02-23 13:04 UTC
Labels: bug

**Comment by crisptrutski** [comment] 2015-02-23 13:05
(clojars updated too)

**Comment by darwin** [comment] 2015-02-24 02:37
Chris, thanks for prompt fix. Using the latest without issues now. https://github.com/darwin/faceboard/commit/ea88ae6c6d834bda96c71514d713838909f1fb2a

**Comment by darwin** [comment] 2015-02-24 02:42
Well, I was too fast. Now I have issues with
    
    lein cljsbuild once

https://gist.github.com/darwin/4ff8d32189358814beb7

This may not be related. Just pasting this FYI. Will investigate it later today.

**Comment by crisptrutski** [comment] 2015-02-24 08:27
@darwin doesn't look related to me

**Comment by darwin** [comment] 2015-02-24 08:44
I spent some time trying to comment out parts of my codebase to pinpoint the problem, but only including matchbox as a dep starts to causing this trouble.

I wanted to vendor matchbox and try to comment out stuff there, but I'm unable to reproduce you build. Are you using boot already for the published jars? My `lein install` does not product required namespaces (I think).

**Comment by crisptrutski** [comment] 2015-02-24 08:48
The deployed snapshot was produced with leiningen. If you're installing locally, make sure you're running `lein do clean, cljx once` first.

**Comment by darwin** [comment] 2015-02-24 09:35
Thanks. I was able to comment out most of the code to isolate the issue:

https://github.com/crisptrutski/matchbox/blob/f2e2615b86930b92598e235bf6c5224ff9423fc5/src/matchbox/core.cljx#L288

IMO that line should not crash the compiler but it does. It seems to be self-referencing definition. Can you rewrite it?

**Comment by crisptrutski** [comment] 2015-02-24 09:55
Wow, yeah that seems to actually break advanced compilatio (realise I hadn't seen your issue as I'd only compiled dev).

It's a typo, fixing

**Comment by darwin** [comment] 2015-02-24 10:24
All good now. Thanks!
